Repository krateoplatformops/authn, pull requests merged in 2024-10, with the labels that each got.

#15 ci: fix workflow update-crd-doc
  .github/workflows/release-tag.yaml
Labels: bug, ci

#17 docs: updated readme to include the detailed Azure-side configuration…
  README.md
Labels: documentation

#19 18 the method for OIDC is get instead of post
  README.md
  internal/routes/auth/oidc/login.go
  internal/routes/auth/oidc/support.go
Labels: bug, documentation
